export type Language = "en" | "fr";

export const translations = {
  en: {
    // App
    appName: "Dental Assistant",
    appTagline: "Professional AI-Powered Care",
    version: "Version 1.0",

    // Language selector
    selectLanguage: "Select Language",
    languageSubtitle: "Choose your preferred language",
    continue: "Continue",
    english: "English",
    french: "Français",

    // Splash screen
    initializing: "Initializing system...",

    // Error screen
    connectionFailed: "Connection Failed",
    troubleshooting: "Troubleshooting:",
    troubleshootingTips: [
      "Check if the backend service is running",
      "Verify network connectivity",
      "Restart the application",
    ],
    tryAgain: "Try Again",

    // Model Setup
    setupTitle: "System Setup",
    setupSubtitle: "Let's configure your AI assistant",
    stepHardware: "Hardware Detection",
    stepDownload: "Model Download",
    stepReady: "Ready",

    // Hardware detection
    analyzingHardware: "Analyzing your system...",
    systemRequirements: "System Requirements",
    hardwareProfile: "Hardware Profile",
    cpuOnly: "CPU Only",
    lowVram: "Low VRAM GPU",
    highVram: "High VRAM GPU",
    recommendedModel: "Recommended Model",
    modelSize: "Model Size",
    estimatedRam: "Estimated RAM",
    downloadSize: "Download Size",
    optimal: "Optimal",

    // Download
    downloadAndContinue: "Download & Continue",
    downloading: "Downloading...",
    downloadingModel: "Downloading AI Model",
    downloadProgress: "This may take several minutes depending on your connection",
    skipDownload: "Skip for now",
    modelReady: "Model Ready",
    modelReadyDesc: "The AI model is already installed and ready to use.",
    continueToApp: "Continue to App",

    // Main Dashboard
    dashboard: "Dashboard",
    uploadAudio: "Upload Audio",
    uploadAudioDesc: "Drag and drop an audio file or click to browse",
    supportedFormats: "Supported formats: WAV, MP3, M4A, OGG (max 10MB)",
    processing: "Processing",
    processingAudio: "Processing your audio...",
    transcribing: "Transcribing audio content",
    transcription: "Transcription",
    transcriptionResult: "Transcription Result",
    analysis: "Analysis",
    analysisResult: "AI Analysis",
    analyzing: "Analyzing content...",
    copyToClipboard: "Copy to clipboard",
    copied: "Copied!",
    newRecording: "New Recording",

    // Errors
    processingError: "Processing Error",
    errorOccurred: "An error occurred",

    // Settings
    settings: "Settings",
    language: "Language",

    // MainDashboard - Header
    aiPoweredDocumentation: "AI-Powered Documentation",
    online: "Online",
    clear: "Clear",

    // MainDashboard - Upload Zone
    uploadAudioRecording: "Upload Audio Recording",
    dropAudioHere: "Drop your audio file here",
    dragAndDropAudio: "Drag and drop your audio file here, or click to browse. We'll transcribe and summarize it automatically.",
    chooseAudioFile: "Choose Audio File",
    maxFileSize: "Maximum file size: 100 MB",

    // MainDashboard - Live Recorder
    liveRecording: "Live Recording",
    recordingPaused: "Recording Paused",
    recordingInProgress: "Recording...",
    recordingReady: "Recording Ready",
    startRecording: "Start Recording",
    stopRecording: "Stop",
    pauseRecording: "Pause",
    resumeRecording: "Resume",
    processRecording: "Process Recording",
    discardRecording: "Discard",
    recordAgain: "Record Again",
    recordFromMicrophone: "Record audio directly from your microphone. Click the button below to start recording your consultation.",
    microphoneError: "Could not access microphone. Please check permissions.",
    localProcessing: "Recording is processed locally on your device",

    // MainDashboard - Processing
    processingAudioTitle: "Processing Audio",
    processingAudioDesc: "Transcribing your audio and generating a medical summary. This may take a moment depending on the file length.",
    transcribingStep: "Transcribing",
    summarizingStep: "Summarizing",
    generatingSmartNote: "Generating SmartNote",
    aiWriting: "AI is writing...",
    generating: "Generating...",
    generatedByAI: "Generated by AI",

    // MainDashboard - Document
    generatedDocument: "Generated Document",
    editableBeforeExport: "Editable before export",
    documentPlaceholder: "Generated document...",
    exportPDF: "Export as PDF",
    copyDocument: "Copy document",

    // MainDashboard - Footer
    aiEngineActive: "AI Engine Active",
    localProcessingFooter: "100% Local Processing",

    // MainDashboard - Steps
    step1Upload: "Upload audio",
    step2Transcription: "AI Transcription",
    step3Document: "Document generated",

    // ProfileSetup
    profileSetupTitle: "Office Setup",
    profileSetupSubtitle: "Enter your professional information",
    fullName: "Full name",
    fullNamePlaceholder: "Dr. John SMITH",
    professionalTitle: "Professional title",
    professionalTitlePlaceholder: "Dental Surgeon",
    officeAddress: "Office address",
    officeAddressPlaceholder: "15 Main Street, London",
    phone: "Phone",
    phonePlaceholder: "020 1234 5678",
    email: "Email",
    emailPlaceholder: "contact@dental-office.com",
    profileInfoText: "This information will be used to generate the header of your documents",

    // PDF Export
    pdfTitle: "Medical Consultation Note",
    pdfDate: "Date",
    pdfPractitioner: "Practitioner",
    pdfContact: "Contact",
    pdfConsultationNotes: "Consultation Notes",
    pdfDisclaimer: "This document was generated with AI assistance. Please verify and validate before archiving or transmission.",
    pdfConfidential: "CONFIDENTIAL - MEDICAL DOCUMENT",
    pdfPage: "Page",

    // Dark Mode
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    theme: "Theme",
    systemTheme: "System",

    // Consultation History
    consultationHistory: "Consultation History",
    consultationHistoryDesc: "Search and browse past consultations",
    searchPlaceholder: "Search consultations... (e.g., molar pain, extraction, root canal)",
    search: "Search",
    noResults: "No consultations found",
    noResultsDesc: "Try a different search query or save your first consultation",
    noHistory: "No consultation history yet",
    noHistoryDesc: "Your SmartNotes will be automatically saved here after generation",
    backToDashboard: "Back to Dashboard",
    viewHistory: "History",
    consultationDate: "Date",
    relevanceScore: "Relevance",
    savedSuccessfully: "Consultation saved",
    saveFailed: "Failed to save consultation",
    ragEnhanced: "AI-Enhanced with medical references",
    ragUnavailable: "Medical references unavailable",
    consultationCount: "consultations",
    knowledgeCount: "medical references",
    recentConsultations: "Recent Consultations",
    searchResults: "Search Results",
    viewFullNote: "View full note",
    closeNote: "Close",
    consultationSaved: "Saved to history",
    exportJSON: "Export JSON",
    exporting: "Exporting\u2026",

    // Confirmation dialogs
    cancel: "Cancel",
    confirmDiscardTitle: "Discard recording?",
    confirmDiscardMessage: "This audio recording will be permanently deleted. This action cannot be undone.",
    confirmDiscardAction: "Discard",
    confirmClearTitle: "Clear all results?",
    confirmClearMessage: "The current transcription and generated document will be lost. Saved consultations in history are not affected.",
    confirmClearAction: "Clear all",
    confirmOverwriteTitle: "Overwrite current document?",
    confirmOverwriteMessage: "Processing a new file will replace the current transcription and document. Make sure you've exported or copied anything you need.",
    confirmOverwriteAction: "Continue",

    // Document restore
    restoreOriginal: "Restore original",
    documentRestored: "Original document restored",
  },

  fr: {
    // App
    appName: "Assistant Dentaire",
    appTagline: "Soins Professionnels Propulsés par l'IA",
    version: "Version 1.0",

    // Language selector
    selectLanguage: "Choisir la Langue",
    languageSubtitle: "Sélectionnez votre langue préférée",
    continue: "Continuer",
    english: "English",
    french: "Français",

    // Splash screen
    initializing: "Initialisation du système...",

    // Error screen
    connectionFailed: "Échec de Connexion",
    troubleshooting: "Dépannage :",
    troubleshootingTips: [
      "Vérifiez si le service backend est en cours d'exécution",
      "Vérifiez la connectivité réseau",
      "Redémarrez l'application",
    ],
    tryAgain: "Réessayer",

    // Model Setup
    setupTitle: "Configuration du Système",
    setupSubtitle: "Configurons votre assistant IA",
    stepHardware: "Détection Matérielle",
    stepDownload: "Téléchargement du Modèle",
    stepReady: "Prêt",

    // Hardware detection
    analyzingHardware: "Analyse de votre système...",
    systemRequirements: "Configuration Requise",
    hardwareProfile: "Profil Matériel",
    cpuOnly: "CPU Uniquement",
    lowVram: "GPU VRAM Faible",
    highVram: "GPU VRAM Élevée",
    recommendedModel: "Modèle Recommandé",
    modelSize: "Taille du Modèle",
    estimatedRam: "RAM Estimée",
    downloadSize: "Taille du Téléchargement",
    optimal: "Optimal",

    // Download
    downloadAndContinue: "Télécharger et Continuer",
    downloading: "Téléchargement...",
    downloadingModel: "Téléchargement du Modèle IA",
    downloadProgress: "Cela peut prendre plusieurs minutes selon votre connexion",
    skipDownload: "Passer pour l'instant",
    modelReady: "Modèle Prêt",
    modelReadyDesc: "Le modèle IA est déjà installé et prêt à l'emploi.",
    continueToApp: "Continuer vers l'Application",

    // Main Dashboard
    dashboard: "Tableau de Bord",
    uploadAudio: "Télécharger Audio",
    uploadAudioDesc: "Glissez-déposez un fichier audio ou cliquez pour parcourir",
    supportedFormats: "Formats supportés : WAV, MP3, M4A, OGG (max 10Mo)",
    processing: "Traitement",
    processingAudio: "Traitement de votre audio...",
    transcribing: "Transcription du contenu audio",
    transcription: "Transcription",
    transcriptionResult: "Résultat de la Transcription",
    analysis: "Analyse",
    analysisResult: "Analyse IA",
    analyzing: "Analyse en cours...",
    copyToClipboard: "Copier dans le presse-papiers",
    copied: "Copié !",
    newRecording: "Nouvel Enregistrement",

    // Errors
    processingError: "Erreur de Traitement",
    errorOccurred: "Une erreur s'est produite",

    // Settings
    settings: "Paramètres",
    language: "Langue",

    // MainDashboard - Header
    aiPoweredDocumentation: "Documentation Propulsée par l'IA",
    online: "En ligne",
    clear: "Effacer",

    // MainDashboard - Upload Zone
    uploadAudioRecording: "Télécharger un Enregistrement Audio",
    dropAudioHere: "Déposez votre fichier audio ici",
    dragAndDropAudio: "Glissez-déposez votre fichier audio ici, ou cliquez pour parcourir. Nous le transcrirons et le résumerons automatiquement.",
    chooseAudioFile: "Choisir un Fichier Audio",
    maxFileSize: "Taille maximale : 100 Mo",

    // MainDashboard - Live Recorder
    liveRecording: "Enregistrement en Direct",
    recordingPaused: "Enregistrement en Pause",
    recordingInProgress: "Enregistrement...",
    recordingReady: "Enregistrement Prêt",
    startRecording: "Démarrer l'Enregistrement",
    stopRecording: "Arrêter",
    pauseRecording: "Pause",
    resumeRecording: "Reprendre",
    processRecording: "Traiter l'Enregistrement",
    discardRecording: "Supprimer",
    recordAgain: "Enregistrer à Nouveau",
    recordFromMicrophone: "Enregistrez l'audio directement depuis votre microphone. Cliquez sur le bouton ci-dessous pour démarrer l'enregistrement de votre consultation.",
    microphoneError: "Impossible d'accéder au microphone. Veuillez vérifier les permissions.",
    localProcessing: "L'enregistrement est traité localement sur votre appareil",

    // MainDashboard - Processing
    processingAudioTitle: "Traitement de l'Audio",
    processingAudioDesc: "Transcription de votre audio et génération d'un résumé médical. Cela peut prendre un moment selon la durée du fichier.",
    transcribingStep: "Transcription",
    summarizingStep: "Résumé",
    generatingSmartNote: "Génération du SmartNote",
    aiWriting: "L'IA écrit...",
    generating: "Génération...",
    generatedByAI: "Généré par l'IA",

    // MainDashboard - Document
    generatedDocument: "Document Généré",
    editableBeforeExport: "Modifiable avant export",
    documentPlaceholder: "Document généré...",
    exportPDF: "Exporter en PDF",
    copyDocument: "Copier le document",

    // MainDashboard - Footer
    aiEngineActive: "Moteur IA Actif",
    localProcessingFooter: "Traitement 100% Local",

    // MainDashboard - Steps
    step1Upload: "Télécharger audio",
    step2Transcription: "Transcription IA",
    step3Document: "Document généré",

    // ProfileSetup
    profileSetupTitle: "Configuration du Cabinet",
    profileSetupSubtitle: "Entrez vos informations professionnelles",
    fullName: "Nom complet",
    fullNamePlaceholder: "Dr Marie DUPONT",
    professionalTitle: "Titre professionnel",
    professionalTitlePlaceholder: "Chirurgien-dentiste",
    officeAddress: "Adresse du cabinet",
    officeAddressPlaceholder: "15, avenue Victor Hugo – 75016 PARIS",
    phone: "Téléphone",
    phonePlaceholder: "01 23 45 67 89",
    email: "Email",
    emailPlaceholder: "contact@cabinet-dentaire.fr",
    profileInfoText: "Ces informations seront utilisées pour générer l'en-tête de vos documents",

    // PDF Export
    pdfTitle: "Note de Consultation Médicale",
    pdfDate: "Date",
    pdfPractitioner: "Praticien",
    pdfContact: "Contact",
    pdfConsultationNotes: "Notes de Consultation",
    pdfDisclaimer: "Ce document a été généré avec l'assistance de l'IA. Veuillez vérifier et valider avant archivage ou transmission.",
    pdfConfidential: "CONFIDENTIEL - DOCUMENT MÉDICAL",
    pdfPage: "Page",

    // Dark Mode
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    theme: "Thème",
    systemTheme: "Système",

    // Consultation History
    consultationHistory: "Historique des Consultations",
    consultationHistoryDesc: "Rechercher et parcourir les consultations passees",
    searchPlaceholder: "Rechercher des consultations... (ex: douleur molaire, extraction, endodontie)",
    search: "Rechercher",
    noResults: "Aucune consultation trouvee",
    noResultsDesc: "Essayez une autre recherche ou enregistrez votre premiere consultation",
    noHistory: "Pas encore d'historique",
    noHistoryDesc: "Vos SmartNotes seront automatiquement sauvegardees ici apres generation",
    backToDashboard: "Retour au Tableau de Bord",
    viewHistory: "Historique",
    consultationDate: "Date",
    relevanceScore: "Pertinence",
    savedSuccessfully: "Consultation sauvegardee",
    saveFailed: "Echec de la sauvegarde",
    ragEnhanced: "Enrichi par les references medicales",
    ragUnavailable: "References medicales indisponibles",
    consultationCount: "consultations",
    knowledgeCount: "references medicales",
    recentConsultations: "Consultations Recentes",
    searchResults: "Resultats de Recherche",
    viewFullNote: "Voir la note",
    closeNote: "Fermer",
    consultationSaved: "Sauvegarde dans l'historique",
    exportJSON: "Exporter JSON",
    exporting: "Export en cours\u2026",

    // Confirmation dialogs
    cancel: "Annuler",
    confirmDiscardTitle: "Supprimer l'enregistrement ?",
    confirmDiscardMessage: "Cet enregistrement audio sera definitivement supprime. Cette action est irreversible.",
    confirmDiscardAction: "Supprimer",
    confirmClearTitle: "Effacer tous les resultats ?",
    confirmClearMessage: "La transcription et le document genere seront perdus. Les consultations sauvegardees dans l'historique ne sont pas affectees.",
    confirmClearAction: "Tout effacer",
    confirmOverwriteTitle: "Remplacer le document actuel ?",
    confirmOverwriteMessage: "Le traitement d'un nouveau fichier remplacera la transcription et le document actuels. Assurez-vous d'avoir exporte ou copie ce dont vous avez besoin.",
    confirmOverwriteAction: "Continuer",

    // Document restore
    restoreOriginal: "Restaurer l'original",
    documentRestored: "Document original restaure",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
